// ACTION TYPES

export const UPLOAD_DATA = 'UPLOAD_DATA'
export const GET_ALL_DATA = 'GET_ALL_DATA'
export const DATA_SELECTOR = 'DATA_SELECTOR'
export const CREATE_NOTE = 'CREATE_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const GET_USER_NOTES = 'GET_USER_NOTES'
export const TOGGLE_MOBILE_NAV = 'TOGGLE_MOBILE_NAV'
// export const INSERT_INTO_TEXT_AREA = 'INSERT_INTO_TEXT_AREA'